import type { PostRow } from "@reddit-scraper/shared";

export const MOCK_POSTS: PostRow[] = [
  {
    id: "mock-1",
    reddit_id: "t3_mock1",
    subreddit: "wholefoods",
    title: "Best deals at Whole Foods this week?",
    author: "savvyshopper42",
    body: "Just noticed the Prime member deals are really good this week. The organic chicken thighs are $3.99/lb and they have a BOGO on the 365 brand pasta sauce. Anyone else finding good deals at their local store?",
    score: 87,
    num_comments: 34,
    url: "https://reddit.com/r/wholefoods/comments/mock1",
    permalink: "/r/wholefoods/comments/mock1/best_deals_at_whole_foods_this_week",
    created_utc: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    scraped_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    reddit_id: "t3_mock2",
    subreddit: "wholefoodscustomers",
    title: "The prepared foods section has gone downhill",
    author: "foodie_critic",
    body: "I used to love the hot bar but the quality has really dropped at my location. The mac and cheese used to be amazing and now it tastes like it sits there all day. The sushi is still great though. Anyone else noticing this trend?",
    score: 142,
    num_comments: 67,
    url: "https://reddit.com/r/wholefoodscustomers/comments/mock2",
    permalink: "/r/wholefoodscustomers/comments/mock2/the_prepared_foods_section",
    created_utc: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    scraped_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    reddit_id: "t3_mock3",
    subreddit: "wholefoods",
    title: "Employee AMA: I work in the bakery department",
    author: "wf_baker_2024",
    body: "Been working in the Whole Foods bakery for 3 years. Happy to answer questions about what's fresh, what's frozen, and what to avoid. Pro tip: the croissants are baked fresh every morning at 6am. If you come after 2pm they're usually picked over.",
    score: 312,
    num_comments: 156,
    url: "https://reddit.com/r/wholefoods/comments/mock3",
    permalink: "/r/wholefoods/comments/mock3/employee_ama_bakery",
    created_utc: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    scraped_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    reddit_id: "t3_mock4",
    subreddit: "wholefoodscustomers",
    title: "Why is the 365 brand disappearing from shelves?",
    author: "brand_loyalist",
    body: "I've noticed several 365 products being replaced by other brands at my local store. The 365 organic peanut butter was my go-to and now they only carry the more expensive options. Is this happening everywhere or just my store?",
    score: 203,
    num_comments: 89,
    url: "https://reddit.com/r/wholefoodscustomers/comments/mock4",
    permalink: "/r/wholefoodscustomers/comments/mock4/365_brand_disappearing",
    created_utc: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    scraped_at: new Date().toISOString(),
  },
  {
    id: "mock-5",
    reddit_id: "t3_mock5",
    subreddit: "wholefoods",
    title: "Prime Day deals at Whole Foods worth checking out",
    author: "deal_hunter_prime",
    body: "Amazon Prime members get an extra 10% off sale items during Prime Day. Stacking this with the weekly deals means some items are 30-40% off. The organic avocados were $0.99 each and the wild-caught salmon was $8.99/lb.",
    score: 456,
    num_comments: 201,
    url: "https://reddit.com/r/wholefoods/comments/mock5",
    permalink: "/r/wholefoods/comments/mock5/prime_day_deals",
    created_utc: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    scraped_at: new Date().toISOString(),
  },
  {
    id: "mock-6",
    reddit_id: "t3_mock6",
    subreddit: "wholefoodscustomers",
    title: "Whole Foods delivery vs in-store: price difference?",
    author: "curious_customer",
    body: "Has anyone compared prices between ordering delivery through Amazon and shopping in-store? I feel like some items are marked up on the app but I haven't done a proper comparison. Would love to see actual data on this.",
    score: 98,
    num_comments: 45,
    url: "https://reddit.com/r/wholefoodscustomers/comments/mock6",
    permalink: "/r/wholefoodscustomers/comments/mock6/delivery_vs_instore",
    created_utc: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    scraped_at: new Date().toISOString(),
  },
];
